### ISSUE TITLE
TransitionMatrix Request

### ISSUE THREAD

**Issue by raphaelchaves** [open-risk/transitionMatrix#20]
Hi all,
I've started to work with python recently, and I'd be so gratefull if you are able to send me a script in Python using the transitionMatrix package, in order to estimate the following approaches:
a) Transition Matrix for the attached sample, considering the Cohort approach
b) Transition Matrix for the attached sample, considering the Hazard rate approach
c) Confidence levels using bootstrap technique

I'm sending as an attached file the output results achieved through a Visual Basic for Applications function. I've been trying to achieve the same results using the Python transitionMatrix package.

Thanks in advance.
Rgs,
Raphael

[Input_RatingTransitionMatrix.txt](https://github.com/open-risk/transitionMatrix/files/6250096/Input_RatingTransitionMatrix.txt)
[Output_RatingTransitionMatrix.xlsx](https://github.com/open-risk/transitionMatrix/files/6250119/Output_RatingTransitionMatrix.xlsx)

**Comment by open-risk** [comment]
Hi Raphael,
the latest commit includes some scripts to address this test case. Unfortunately the included data set is not sufficiently documented or clean enough to allow unambiguous replication. But it still useful as an example of a realistic situation so with this update there are some scripts to illustrate:

- You can check out the data [cleaning script in the examples](https://github.com/open-risk/transitionMatrix/blob/master/examples/python/data_cleaning_example.py) for one way of handling the ambiguous data issues
- Once we have a clean data set  we can apply both the cohort and aalen-johansen estimators and [compare](https://github.com/open-risk/transitionMatrix/blob/master/examples/python/estimate_matrix.py).  The result (e.g. for one-year matrix) is pretty close, closer than your calculation
